db.ordenadores.insertOne(
    /*1*/ {
            Modelo:"MSI MAG Codex 5 11TC-668XIB", 
            precio:1499.9, 
            Marca:"MSI",
            Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}],
            Destinado: "Gaming",
            Componentes:{
                Placabase:{
                            Marca: "MSI", 
                            Modelo: "B460M",
                            Formato: "ATX",
                            Socket: ["LGA","PGA"],
                            Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport","USB 2.0"],
                            TipoUSB: [2.0, 3.0, 3.1],
                            LEDS: true
            },
                RAM:{      
                           Modelo: "Kingston FURY Beast",  
                           LEDS: false,
                           Cantidad: 2,
                           Memoria: 32,
                           DDR: 4  
            },
                Procesador:{
                            Modelo: "Intel Core i7-11700",
                            Marca: "Intel",
                            Core: 7,
                            Generacion: 11,
                            GHZ: 3.5,
                            MAXGHZ: 4.9,
                            Grafica: true
            },                 
                Grafica: {
                            Modelo:"RTX 3060 VENTUS 2X",
                            Marca:"Nvidia"
            },    
                Fuente: {
                            Modelo:"Owlotech BPS",
                            Marca:"Owlotech",
                            Vatios: 750,
                            Certificacion: true,
                            Tipocertificacion: "bronze"
            },
                Almacenamiento:{
                            Discos: 2,
                            Tipos: ["HDD", "SSD"],
                            Marca: ["Seagate", "Samsung"],
                            TB: 1.5
            },
                Caja:{
                            Modelo:"MSI MAG Forge",
                            Marca:"MSI",
                            Ventiladores: 4,
                            Puertos: ["USB 3.0", "USB 2.0","Jack"],
                            TipoUSB: [2.0, 3.0, 3.1]
                            
            },
                Refrigeracion:{
                            Modelo:"Cooler Master LC240E",
                            Marca:"Cooler Master",
                            Tipo:"Liquida",
                            Ventiladores: 2   
             },

                Hub: [  {
                    Tipo:"LEDS",
                    Conectores: 6
                }, {
                    Tipo:"FAN",
                    Conectores: 6

                 }   ]
            
        }},
     )

    
    db.ordenadores.insertMany([
    
    /*2*/   {Modelo:"Lenovo IdeaCentre G5 14IMB05", precio:761.62, Marca:"Lenovo", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Gaming", Componentes:{ Placabase:{ Marca: "ASUS", Modelo: "Asus TUF GAMING B550-PLUS WI-FI", Formato: "ATX", Socket: ["LGA","ZIF"], Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport","USB 2.0","Jack"], LEDS: true}, RAM:{Modelo: "Kingston FURY Beast DDR4", Cantidad: 1, LEDS: true, Memoria: 8, DDR: 4}, Procesador:{ Modelo: "Intel Core i5-10400", Marca: "Intel", Core: 5, Generacion: 10, GHZ: 2.9, MAXGHZ: 4.3, Grafica: true}, Grafica: { Modelo:"Nvidia GeForce GTX 1660 SUPER", Marca:"Nvidia"}, Fuente: {Modelo:"Corsair CX550M", Marca:"Corsair", Vatios: 500, Certificacion: true, Tipocertificacion:"bronze"}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Kingston"], TB: 1.5}, Caja:{Modelo:"Tempest Phantom", Marca:"Tempest", Ventiladores: 3, Puertos: ["USB 3.0, USB 2.0, Jack 3.0"]}, Refrigeracion:{Modelo:"Cooler Master Hyper 212 RGB", Marca:"Cooler Master", Tipo:"Aire", Ventiladores: 1}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*3*/   {Modelo:"MSI MAG Infinite S 10SH-094XIB", precio:999.9, Marca:"MSI", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Gaming", Componentes:{ Placabase:{ Marca: "MSI", Modelo: "MSI B550M PRO VDH", Formato: "Micro-ATX", Socket: ["LGA","ZIF"], Puertos: ["USB 3.0", "HDMI, RJ45", "Displayport","USB 2.0"], LEDS: true}, RAM:{Modelo: "Corsair Vengeance LPX", LEDS: false, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "Intel Core i7-10700F", Marca: "Intel", Core: 10, Generacion: 10, GHZ: 3.2, MAXGHZ: 4.7, Grafica: false}, Grafica: { Modelo:"GTX 1660 VENTUS XS 6G", Marca:"Nvidia"}, Fuente: {Modelo:"Thermaltake Smart RGB", Marca:"Thermaltake", Vatios: 700, Certificacion: true, Tipocertificacion:"bronze"}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Crucial"], TB: 2}, Caja:{Modelo:"Aerocool Wave V3", Marca:"Aerocool", Ventiladores: 4, Puertos: ["USB 2.0, USB 3.0, Jack "]}, Refrigeracion:{Modelo:"Tempest Basic Cooler", Marca:"Tempest", Tipo:"Aire", Ventiladores: 1}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*4*/   {Modelo:"MSI MAG Infinite S 10SH-096XIB", precio:907.12, Marca:"MSI", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Gaming", Componentes:{ Placabase:{ Marca: "Gigabyte", Modelo: "Gigabyte B450M DS3H", Formato: "ATX", Socket: ["LGA","BGA"], Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport","USB 2.0"], LEDS: true}, RAM:{Modelo: "Team Group Delta White RGB",  LEDS: true, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "i5-10400F", Marca: "Intel", Core: 5, Generacion: 10, GHZ: 3.0, MAXGHZ: 4.2, Grafica: true}, Grafica: { Modelo:"RTX 2060", Marca:"Nvidia"}, Fuente: {Modelo:"Mars Gaming Vulcano", Marca:"Mars Gaming", Vatios: 750, Certificacion: true, Tipocertificacion:"silver"}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Samsung"], TB: 1.5}, Caja:{Modelo:"Tempest Spectra RGB", Marca:"Tempest", Ventiladores: 4, Puertos: ["USB 2.0","USB 3.0, Jack"]}, Refrigeracion:{Modelo:"Corsair Hydro H100x", Marca:"Corsair", Tipo:"Liquida", Ventiladores: 2}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*5*/   {Modelo:"Millenium Machine 1 Mini REKSA", precio:1204.91, Marca:"Millenium", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Gaming", Componentes:{ Placabase:{ Marca: "MSI", Modelo: "MSI MAG B560M BAZOOKA", Formato:"ATX", Socket: ["LGA","BGA","ZIF"], Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport","USB 2.0"], LEDS: true}, RAM:{Modelo: "Corsair Vengeance RGB", Cantidad:2,  LEDS: true, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "Intel Core i5 10400F", Marca: "Intel", Core: 5, Generacion: 10, GHZ: 2.5, MAXGHZ: 4.5, Grafica: false}, Grafica: { Modelo:"RTX 2060", Marca:"Nvidia"}, Fuente: {Modelo:"Corsair RM Series RM750", Marca:"Corsair", Vatios: 750, Certificacion: false}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Crucial", "Samsung"], TB: 1.5}, Caja:{Modelo:"Nfortec Draco V2", Marca:"Nfortec", Ventiladores: 4, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Cooler Master MasterLiquid ML240L", Marca:"Cooler Master", Tipo:"Liquida", Ventiladores: 2}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*6*/   {Modelo:"HP OMEN 30L GT13-1017ns", precio:1511.70, Marca:"HP", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Gaming", Componentes:{ Placabase:{ Marca: "ASUS", Modelo: "Asus PRIME Z590-P", Formato: "ATX", Socket: ["LGA","BEA"], Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport","USB 2.0"], LEDS: true}, RAM:{Modelo: "Corsair Vengeance RGB",  LEDS: true, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "Intel Core I5 10400", Marca: "Intel", Core: 5, Generacion: 10, GHZ: 3.5, MAXGHZ: 4.5, Grafica: true}, Grafica: { Modelo:"RTX 2080", Marca:"Nvidia"}, Fuente: {Modelo:"Nox Urano VX", Marca:"Nox", Vatios: 650, Certificacion: true, Tipodecertificacion:"bronze"}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Crucial", "Seagate"], TB: 1.5}, Caja:{Modelo:"Tempest ATX CASE RGB", Marca:"Tempest gaming", Ventiladores: 4, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Corsair ICUE H100i ELITE CAPELLIX", Marca:"Corsair", Tipo:"Liquida", Ventiladores: 2}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*7*/   {Modelo:"Legion-Q Tracker Lambda", precio:679.9, Marca:"Legion-Q", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Ofimatica", Componentes:{ Placabase:{ Marca: "ASUS", Modelo: "Asus PRIME Z590-P", Formato: "Micro-ATX", Socket: ["LGA",""], Puertos: ["USB 3.0", "HDMI", "RJ45","USB 2.0"], LEDS: true}, RAM:{Modelo: "Corsair Vengeance LPX DDR4",  LEDS: true, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "AMD Ryzen 7 3700X", Marca: "AMD", Core: 7, Generacion: 3, GHZ: 3.7, MAXGHZ: 5.2, Grafica: true}, Grafica: { Modelo:"RTX 3060", Marca:"Nvidia"}, Fuente: {Modelo:"Nfortec Sagitta RGB", Marca:"Nfortec", Vatios: 750, Certificacion: true, Tipocertificacion:"gold"}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Crucial"], TB: 2}, Caja:{Modelo:"Corsair ICUE 4000X", Marca:"Corsair", Ventiladores: 4, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Nfortec Hydrus V2 120", Marca:"Nfortec", Tipo:"Liquida", Ventiladores: 1}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*8*/   {Modelo:"MSI MAG Infinite S 10SC-095XIB", precio:1149.9, Marca:"MSI", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Gaming", Componentes:{ Placabase:{ Marca: "Gigabyte", Modelo: "Gigabyte B450M DS3H", Formato: "Mini-ATX", Socket: ["ZIF","LGA"], Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport","USB 2.0"], LEDS: true}, RAM:{Modelo: "Team Group Delta White RGB",  LEDS: true, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "Intel Core i7-12700K", Marca: "Intel", Core: 7, Generacion: 12, GHZ: 3.7, MAXGHZ: 5.2, Grafica: true}, Grafica: { Modelo:"RTX 2070 ti", Marca:"Nvidia"}, Fuente: {Modelo:"Corsair TX850M 850W", Marca:"Corsair", Vatios: 850, Certificacion: true, Tipocertificacion:"silver"}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Crucial"], TB: 1.5}, Caja:{Modelo:"Tempest Ghost Cristal Templado", Marca:"Tempest Gaming", Ventiladores: 4, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Nfortec Hydrus RGB 240", Marca:"Nfortec", Tipo:"Liquida", Ventiladores: 2}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*9*/   {Modelo:"HP Pavilion TP01-1014ns", precio:529.9, Marca:"HP", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Ofimatica", Componentes:{ Placabase:{ Marca: "ASUS", Modelo: "Asus PRIME Z590-P", Formato: "ATX", Socket: ["ZIF","LGA"], Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport","USB 2.0"], LEDS: false}, RAM:{Modelo: "Corsair Vengeance LPX DDR4",  LEDS: false, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "AMD Ryzen 7 3800X", Marca: "AMD", Core: 7, Generacion: 3, GHZ: 2.5, MAXGHZ: 4.1, Grafica: true}, Grafica: { Modelo:"AMD Radeon RX 6600", Marca:"AMD"}, Fuente: {Modelo:"EVGA W1 600W 80 Plus", Marca:"EVGA", Vatios: 600, Certificacion: false}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Crucial"], TB: 2}, Caja:{Modelo:"Corsair ICUE 4000X RGB", Marca:"Corsair", Ventiladores: 4, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Nfortec Hydrus RGB 120", Marca:"Nfortec", Tipo:"Liquida", Ventiladores: 2}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*10*/  {Modelo:"Acer Aspire TC-1660", precio:599.9, Marca:"Acer", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Gaming", Componentes:{ Placabase:{ Marca: "MSI", Modelo: "MSI B450M Mortar Max", Formato: "ITX", Socket: ["LGA","BGA"], Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport","USB 2.0"], LEDS: false}, RAM:{Modelo: "Crucial DDR4 2400 PC4 19200 CL17",  LEDS: false, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "Intel Core I5 10400", Marca: "Intel", Core: 5, Generacion: 10, GHZ: 3.2, MAXGHZ: 4.1, Grafica: false}, Grafica: { Modelo:"MSI GeForce RTX 3080 GAMING", Marca:"Nvidia"}, Fuente: {Modelo:"Tempest Gaming PSU PRO 850W", Marca:"Tempest Gaming", Vatios: 850, Certificacion: true, Tipocertificacion:"bronze"}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Crucial"], TB: 1.5}, Caja:{Modelo:"NOX Hummer Zero Core Black Edition", Marca:"NOX", Ventiladores: 3, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Nfortec Hydrus RGB 120", Marca:"Nfortec", Tipo:"Liquida", Ventiladores: 2}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*11*/  {Modelo:"IOX Gaming 870", precio:679.9, Marca:"IOX Gaming", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Ofimatica", Componentes:{ Placabase:{ Marca: "Gigabyte", Modelo: "Gigabyte B450M DS3H", Formato: "ITX", Socket: ["ZIF","LGA"], Puertos: ["USB 3.0", "RJ45", "Displayport","USB 2.0"], LEDS: true}, RAM:{Modelo: "Crucial DDR4 2400 PC4 19200 CL17",  LEDS: false, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "Intel Core I5 10400", Marca: "Intel", Core: 5, Generacion: 10, GHZ: 3.8, MAXGHZ: 4.5, Grafica: true}, Grafica: { Modelo:"AMD Radeon RX 6700 XT", Marca:"AMD"}, Fuente: {Modelo:"Seasonic B12 BC Series 550W", Marca:"Seasonic", Vatios: 550, Certificacion: true, Tipocertificacion:"bronze"}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Crucial"], TB: 1}, Caja:{Modelo:"Tempest Ghost Cristal Templado", Marca:"Tempest Gaming", Ventiladores: 4, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Tempest PRO Cooler 4Pipes", Marca:"Tempest Gaming", Tipo:"Aire", Ventiladores: 2}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*12*/  {Modelo:"MSI PBB560M", precio:1299.9, Marca:"MSI", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Gaming", Componentes:{ Placabase:{ Marca: "MSI", Modelo: "MSI MAG B560M BAZOOKA", Formato: "ATX", Socket: ["LGA","BGA"], Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport,USB 2.0"], LEDS: true}, RAM:{Modelo: "Team Group Delta White RGB",  LEDS: true, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "Intel Core i7-12700K", Marca: "Intel", Core: 7, Generacion: 12, GHZ: 4.3, MAXGHZ: 5.2, Grafica: true}, Grafica: { Modelo:"EVGA GeForce RTX 3070 XC3", Marca:"Nvidia"}, Fuente: {Modelo:"Corsair SF750 750W", Marca:"Corsair", Vatios: 750, Certificacion: true, Tipocertificacion: "silver"}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Crucial"], TB: 2.5}, Caja:{Modelo:"Bitfenix Pack Nova Mesh TG", Marca:"Bitfenix", Ventiladores: 2, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Hiditec C12 PWM Ventilador ", Marca:"Hiditec", Tipo:"Liquida", Ventiladores: 2}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*13*/  {Modelo:"PC Clon PB B460M", precio:1249.9, Marca:"PC Clon", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Gaming", Componentes:{ Placabase:{ Marca: "ASUS", Modelo: "Asus PRIME Z590-P", Formato: "ATX", Socket: ["ZIF","LGA"], Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport","USB 2.0"], LEDS: true}, RAM:{Modelo: "Crucial DDR4 2400 PC4 19200 CL17",  LEDS: false, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "Intel Core I5 10400", Marca: "Intel", Core: 5, Generacion: 11, GHZ: 3.2, MAXGHZ: 4.5, Grafica: false}, Grafica: { Modelo:"MSI GeForce RTX 3080 GAMING", Marca:"Nvidia"}, Fuente: {Modelo:"EVGA Supernova 750 GT 750W", Marca:"Evga", Vatios: 750, Certificacion: false}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Samsung"], TB: 3}, Caja:{Modelo:"NOX Hummer Zero Core Black Edition", Marca:"NOX", Ventiladores: 4, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Corsair iCUE H100i RGB PRO XT", Marca:"Corsair", Tipo:"Liquida", Ventiladores: 2}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*14*/  {Modelo:"Lenovo Legion T5 28IMB05", precio:1811.45, Marca:"Lenovo", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Gaming", Componentes:{ Placabase:{ Marca: "ASUS", Modelo: "Asus PRIME Z590-P", Formato: "ATX", Socket: ["LGA","BGA"], Puertos: ["HDMI", "RJ45", "USB 2.0"], LEDS: true}, RAM:{Modelo: "Corsair Vengeance RGB",  LEDS: true, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "Intel Core i7-12700K", Marca: "Intel", Core: 7, Generacion: 11, GHZ: 2.5, MAXGHZ: 4.5, Grafica: true}, Grafica: { Modelo:"AMD Radeon RX 6600", Marca:"AMD"}, Fuente: {Modelo:"Corsair RM Series RM850 850W", Marca:"Corsair", Vatios: 850, Certificacion: true, Tipocertificacion: "gold"}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Crucial"], TB: 2}, Caja:{Modelo:"Tempest Ghost Cristal Templado", Marca:"Tempest Gaming", Ventiladores: 4, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Tempest PRO Cooler 4Pipes", Marca:"Tempest Gaming", Tipo:"Aire", Ventiladores: 1}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*15*/  {Modelo:"Lenovo IdeaPad 3 15ARH05", precio:799.9, Marca:"Lenovo", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Ofimatica", Componentes:{ Placabase:{ Marca: "MSI", Modelo: "MSI B450M Mortar Max", Formato: "Mini-ATX", Socket: ["ZIF","LGA"], Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport","USB 2.0"], LEDS: true}, RAM:{Modelo: "Corsair Vengeance LPX DDR4",  LEDS: true, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "AMD Ryzen 7 3800X", Marca: "AMD", Core: 7, Generacion: 11, GHZ: 3.6, MAXGHZ: 4.2, Grafica: true}, Grafica: { Modelo:"AMD Radeon RX 6700 XT", Marca:"AMD"}, Fuente: {Modelo:"Thermaltake TR2 S 700W", Marca:"Thermaltake", Vatios: 700, Certificacion: false, Tipocertificacion:"bronze"}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Samsung", "Seagate"], TB: 1.5}, Caja:{Modelo:"Tempest ATX CASE RGB", Marca:"Tempest Gaming", Ventiladores: 4, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Corsair iCUE H100i RGB PRO XT", Marca:"Corsair", Tipo:"Liquida", Ventiladores: 2}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*16*/  {Modelo:"Acer Nitro 5 AN517-41", precio:1479.9, Marca:"Acer", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Gaming", Componentes:{ Placabase:{ Marca: "Gigabyte", Modelo: "Gigabyte B450M DS3H", Formato: "ATX", Socket: ["ZIF","LGA"], Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport","USB 2.0"], LEDS: true}, RAM:{Modelo: "Corsair Vengeance LPX DDR4",  LEDS: false, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "AMD Ryzen 7 3700X", Marca: "AMD", Core: 7, Generacion: 3, GHZ: 2.5, MAXGHZ: 4.5, Grafica: true}, Grafica: { Modelo:"MSI GeForce RTX 3080 GAMING", Marca:"Nvidia"}, Fuente: {Modelo:"EVGA Supernova 750 GT 750W", Marca:"Evga", Vatios: 750, Certificacion: false}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Crucial"], TB: 1}, Caja:{Modelo:"Bitfenix Pack Nova Mesh TG", Marca:"Bitfenix", Ventiladores: 2, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Nfortec Hydrus RGB 120", Marca:"Nfortec", Tipo:"Liquida", Ventiladores: 1}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*17*/  {Modelo:"ASUS ROG Strix G513IC-HN004T", precio:1199.9, Marca:"ASUS", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Gaming", Componentes:{ Placabase:{ Marca: "MSI", Modelo: "MSI MAG B560M BAZOOKA", Formato: "ATX", Socket: ["ZIF","LGA"], Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport","USB 2.0"], LEDS: true}, RAM:{Modelo: "Team Group Delta White RGB",  LEDS: true, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "AMD Ryzen 7 3700X", Marca: "AMD", Core: 7, Generacion: 11, GHZ: 3.5, MAXGHZ: 4.8, Grafica: false}, Grafica: { Modelo:"AMD Radeon RX 6600", Marca:"AMD"}, Fuente: {Modelo:"Corsair RM Series RM850 850W", Marca:"Corsair", Vatios: 850, Certificacion:true, Tipocertificacion:"bronze" }, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Samsung"], TB: 1.5}, Caja:{Modelo:"Bitfenix Pack Nova Mesh TG", Marca:"Bitfenix", Ventiladores: 4, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Nfortec Hydrus RGB 120", Marca:"Nfortec", Tipo:"Liquida", Ventiladores: 2}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},,
    /*18*/  {Modelo:"MSI Bravo 15 B5DD-007XES", precio:808.9, Marca:"MSI", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Gaming", Componentes:{ Placabase:{ Marca: "MSI", Modelo: "MSI B450M Mortar Max", Formato: "ATX", Socket: ["LGA","BGA"], Puertos: ["USB 3.0", "HDMI", "RJ45", "Displayport","USB 2.0"], LEDS: true}, RAM:{Modelo: "Crucial DDR4 2400 PC4 19200 CL17",  LEDS: false, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "Intel Core I5 10400", Marca: "Intel", Core: 5, Generacion: 10, GHZ: 2.5, MAXGHZ: 4.5, Grafica: true}, Grafica: { Modelo:"EVGA GeForce RTX 3070 XC3", Marca:"Nvidia"}, Fuente: {Modelo:"Corsair RM Series RM850 850W", Marca:"Corsair", Vatios: 850, Certificacion: true, Tipocertificacion:"bronze"}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Crucial", "Seagate"], TB: 1.5}, Caja:{Modelo:"Tempest ATX CASE RGB", Marca:"Tempest Gaming", Ventiladores: 3, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Corsair iCUE H100i RGB PRO XT", Marca:"Corsair", Tipo:"Liquida", Ventiladores: 2}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},,
    /*19*/  {Modelo:"HP 15s-fq0013ns", precio:499.9, Marca:"MSI", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Ofimatica", Componentes:{ Placabase:{ Marca: "MSI", Modelo: "MSI MAG B560M BAZOOKA", Formato: "ATX", Socket: ["ZIF","LGA"], Puertos: ["USB 3.0", "HDMI", "RJ45","USB 2.0"], LEDS: true}, RAM:{Modelo: "Crucial DDR4 2400 PC4 19200 CL17",  LEDS: false, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "Intel Core I5 10400", Marca: "Intel", Core: 5, Generacion: 10, GHZ: 2.5, MAXGHZ: 4.0, Grafica: true}, Grafica: { Modelo:"AMD Radeon RX 6700 XT", Marca:"AMD"}, Fuente: {Modelo:"Thermaltake TR2 S 700W", Marca:"Thermaltake", Vatios: 700, Certificacion: false}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Seagate", "Crucial"], TB: 1.5}, Caja:{Modelo:"NOX Hummer Zero Core Black Edition", Marca:"NOX", Ventiladores: 4, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Hiditec C12 PWM Ventilador CPU", Marca:"Hiditec", Tipo:"Aire", Ventiladores: 1}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    /*20*/  {Modelo:"Huawei D 15 2021", precio:399.9, Marca:"Huawei", Rangodefechadecompra:[{FechaInicio: new Date("2020-01-01")}, {fechaExpedicion: new Date("2025-02-04")}], Destinado: "Ofimatica", Componentes:{ Placabase:{ Marca: "ASUS", Modelo: "Asus PRIME Z590-P", Formato: "Micro-ATX", Socket: ["LGA","ZIF"], Puertos: ["USB 3.0", "HDMI","VGA", "RJ45", "Displayport,USB 2.0"], LEDS: true}, RAM:{Modelo: "Corsair Vengeance RGB",  LEDS: true, Memoria: 16, DDR: 4}, Procesador:{ Modelo: "AMD Ryzen 7 3800X", Marca: "AMD", Core: 7, Generacion: 11, GHZ: 3.5, MAXGHZ: 4.2, Grafica: true}, Grafica: { Modelo:"AMD Radeon RX 6600", Marca:"AMD"}, Fuente: {Modelo:"EVGA Supernova 750 GT 750W", Marca:"Evga", Vatios: 750, Certificacion: false}, Almacenamiento:{Discos: 2, Tipos: ["HDD", "SSD"], Marca: ["Crucial", "Seagate"], TB: 2}, Caja:{Modelo:"Tempest ATX CASE RGB", Marca:"Tempest Gaming", Ventiladores: 4, Puertos: ["USB 2.0","USB 3.0","Jack"]}, Refrigeracion:{Modelo:"Nfortec Hydrus RGB 120", Marca:"Nfortec", Tipo:"Liquida", Ventiladores: 1}, Hub:[{Tipo:"LEDS",Conectores: 6}, {Tipo:"FAN",Conectores: 6}]}},
    
    
    
    
        
    
    ]
    )
    
    